spring:
  application:
    name: golden-harvest

  datasource:
    url: jdbc:mariadb://localhost:3306/goldenharvest
    username: goldenharvest
    password: goldenharvest
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

server:
  port: 8088
