spring:
  application:
    name: golden-harvest

  profiles:
    active: local

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  datasource:
    url: jdbc:mariadb://localhost:3306/goldenharvest
    username: goldenharvest
    password: goldenharvest
  driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

file:
  upload-dir: ./uploads

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

kamis:
  cert:
    key: ${KAMIS_CERT_KEY}
    id: ${KAMIS_CERT_ID}
jwt:
  secret-key: v9y$B&E)H@McQfTjWnZr4u7x!A%C*F-JaNdRgUkXp2s5v8y/B?E(G+KbPeShVmYp
  access-token-expiration: 3600000  # 1시간
  refresh-token-expiration: 1209600000  # 1일

server:
  port: 8088
