spring:
  application:
    name: golden-harvest
  mvc:
    static-path-pattern: /files/** # 브라우저 요청 URL 패턴
  web:
    resources:
      static-locations: file:./uploads/  # 실제 파일 위치 (프로젝트 루트의 uploads 폴더)
  profiles:
    active: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      # 앞서 만든 JacksonJsonSerializer가 자동 적용되도록 설정 가능
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      group-id: golden.harvest.inventory.processor
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # 모든 패키지 역직렬화 허용

  datasource:
    url: jdbc:mariadb://harvest-db.crmia2oe03uh.ap-northeast-2.rds.amazonaws.com:3306/goldenharvest
    username: admin
    password: harvest123
  driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #수정 금지
    show-sql: true
    properties:
      hibernate:
        format_sql: true

file:
  upload-dir: ./uploads

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

kamis:
  cert:
    key: ${KAMIS_CERT_KEY}
    id: ${KAMIS_CERT_ID}
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000  # 1시간
  refresh-token-expiration: 1209600000  # 1일

server:
  port: 8088