spring:
    application:
        name: golden-harvest

datasource:
    url: jdbc:mysql://localhost:3306/goldenharvest?serverTimezone=Asia/Seoul
    username: goldenharvest
    password: goldenharvest
    driver-class-name: org.mysql.jdbc.Driver

jpa:
    hibernate:
        ddl-auto: update
    show-sql: true
    properties:
        hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.MySQLDialect

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml
server:
  port: 8088