spring:
  application:
    name: golden-harvest
  mvc:
    static-path-pattern: /files/** # 브라우저 요청 URL 패턴
  web:
    resources:
      static-locations: file:./uploads/  # 실제 파일 위치 (프로젝트 루트의 uploads 폴더)
  profiles:
    active: local

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  datasource:
    url: jdbc:mariadb://localhost:3306/goldenharvest
    username: goldenharvest
    password: goldenharvest
  driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

file:
  upload-dir: ./uploads

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml

kamis:
  cert:
    key: ${kamis.cert.key}
    id: ${kamis.cert.id}
jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: 3600000  # 1시간
  refresh-token-expiration: 1209600000  # 1일

server:
  port: 8088